### ISSUE TITLE
[PE-D][Tester D] Differences in outcomes for the features add_dish from the user guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-4/tp#103]
The outcome is different from the user guide.

![image.png](https://raw.githubusercontent.com/tsx0314/ped/main/files/22c73767-f816-4722-bc53-99bfd13dbace.png)

It only shows 'add dish' without specifying the details

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: tsx0314/ped#2

**Comment by Zeno-Zr** [comment]
Bug Fixes for Dish
[68cceee0b4aadb197997405eca9db0ca0442dfa3 ](https://github.com/AY2223S2-CS2113-W15-4/tp/commit/68cceee0b4aadb197997405eca9db0ca0442dfa3)
