### ISSUE TITLE
[PE-D][Tester B] Duplicate dishes able to be added even with different prices

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W15-4/tp#122]
Considering that this is a restaurant manager, the idea of having duplicate dishes should not be allowed as this will just confuse the staff on which order to add during service.

Duplicate names and prices are able to be added to the list of dishes.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ChubbsBunns/ped#9

**Comment by Zeno-Zr** [comment]
the application's TA is restaurant managers and other staff members won't be using this.
