### ISSUE TITLE
[PE-D][Tester E] Empty list shown for find_dish

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W15-4/tp#126]
![Screenshot (1041).png](https://raw.githubusercontent.com/xiaoge26/ped/main/files/79f0a598-d14e-409f-83d5-5f40735e5112.png)
It may be better to show a message saying "there is no dish matching the keyword you entered" etc to guide the user.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: xiaoge26/ped#8

**Comment by Zeno-Zr** [comment]
Bug Fixes for Dish
[68cceee0b4aadb197997405eca9db0ca0442dfa3](https://github.com/AY2223S2-CS2113-W15-4/tp/commit/68cceee0b4aadb197997405eca9db0ca0442dfa3)
