### ISSUE TITLE
[PE-D][Tester A] find_dish not printing any error/exception message if the keyword is not found in the list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-W15-4/tp#128]
the `find_dish` command does not print any message if the keyword provided is not found. Also, does not work if the keyword is a substring of the dish names, as shown here:

![image.png](https://raw.githubusercontent.com/Ansenn/ped/main/files/4365c90c-3fff-47bd-a749-e14f29b69045.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Ansenn/ped#5

**Comment by Zeno-Zr** [comment]
Bug Fixes for Dish
[68cceee0b4aadb197997405eca9db0ca0442dfa3](https://github.com/AY2223S2-CS2113-W15-4/tp/commit/68cceee0b4aadb197997405eca9db0ca0442dfa3)
