### ISSUE TITLE
for find_meeting, show the full string like view_meeting

### ISSUE THREAD

**Issue by Stella1585** [AY2223S2-CS2113-W15-4/tp#74]

**Comment by darrenangwx** [comment]
Currently only meeting name is printed out. do it like deadlines the below if possible
![image](https://user-images.githubusercontent.com/15652564/230354692-e83daf95-fa16-4a81-b4f6-d647cdc62bc5.png)

**Comment by darrenangwx** [comment]
still not fixed. see if you have time to do this @douph810975
